// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpckxxjjptomjbvfduag.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxwY2t4eGpqcHRvbWpidmZkdWFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwODAwMzYsImV4cCI6MjA2MjY1NjAzNn0.DS5APnbIS3S8Lw8taNVsR23-6dc4T-j8hZfOobsrFX4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);